# -*- coding: utf-8 -*-
"""Cars Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TWEdU-0ANV_S149tFbPDb_fh3rH1ac1d

# Working on Real Project with Python

## (A part of Big Data Analysis)

***

# Cars Dataset
***
Here, 
The data of different cars is given with their specifications.


This data is available as a CSV file. We are going to analyze this data set using the Pandas DataFrame.

----
"""

import pandas as pd

car = pd.read_csv(r"/content/Cars Data1.csv")

car.shape



"""1) Instruction ( For Data Cleaning ) 
- Find all Null Value in the dataset. If there is any null value in any column, then fill it with the mean of that column. 
"""

car.isnull().sum()

car.head(432)

car['Cylinders'].fillna(car['Cylinders'].mean(), inplace = True)

"""----

2) Question ( Based on Value Counts )
- Check what are the different types of Make are there in our dataset. And, what is the count (occurrence) of each Make in the data
?
"""

car.head(5)

car['Make'].value_counts()

"""----

3) Instruction ( Filtering )
- Show all the records where Origin is Asia or Europe.
"""

car.head(5)

car[car['Origin'].isin(['Asia', 'Europe'])]

car['Origin'].value_counts()

158 + 123

"""----

4) Instruction ( Removing unwanted records )
- Remove all the records (rows) where Weight is above 4000.
"""

car.head(2)

car[~(car['Weight'] > 4000)]

428 - 103

"""-----

5) Instruction ( Applying function on a column )
- Increase all the values of 'MPG_City' column by 3.
"""

car.head(2)

car[car['Horsepower']>200]

car['MPG_City'] =  car['MPG_City'].apply(lambda x:x+3)

car

"""----

----

-----

----

### By -Dr.Bomma.Ramakrishna
"""